import {NAME_SPACE} from './constants';

export const SPOTIFY_LOG_IN_INITIATED = `${NAME_SPACE}/SPOTIFY_LOG_IN_INITIATED`;
export const SPOTIFY_LOG_IN_SUCCESS = `${NAME_SPACE}/SPOTIFY_LOG_IN_SUCCESS`;
export const SPOTIFY_LOG_IN_FAILURE = `${NAME_SPACE}/SPOTIFY_LOG_IN_FAILURE`;
export const SPOTIFY_AUTH_CALLBACK_RECEIVED = `${NAME_SPACE}/SPOTIFY_AUTH_CALLBACK_RECEIVED`;
export const SPOTIFY_STORED_CREDENTIALS_LOADED = `${NAME_SPACE}/SPOTIFY_STORED_CREDENTIALS_LOADED`;
export const SPOTIFY_LOG_OUT = `${NAME_SPACE}/SPOTIFY_LOG_OUT`; // TODO: rename to SPOTIFY_CLEAR_SESSION
