export const SPOTIFY_LOG_IN_INITIATED = 'SPOTIFY_LOG_IN_INITIATED';
export const SPOTIFY_LOG_IN_SUCCESS = 'SPOTIFY_LOG_IN_SUCCESS';
export const SPOTIFY_LOG_IN_FAILURE = 'SPOTIFY_LOG_IN_FAILURE';
export const SPOTIFY_AUTH_CALLBACK_RECEIVED = 'SPOTIFY_AUTH_CALLBACK_RECEIVED';
export const SPOTIFY_STORED_CREDENTIALS_LOADED = 'SPOTIFY_STORED_CREDENTIALS_LOADED';
export const SPOTIFY_LOG_OUT = 'SPOTIFY_LOG_OUT'; // TODO: rename to SPOTIFY_CLEAR_SESSION

export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_DEVICES = 'FETCH_DEVICES';
export const PLAY = 'PLAY';
export const REFRESH_SESSION = 'REFRESH_SESSION';
